# Generated by Django 2.1.7 on 2019-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schapp', '0007_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
